- 3 subt params
- 2 pf params

In [16]:
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt

import pandas as pd
import seaborn as sns
import os
from statsmodels.stats.multitest import fdrcorrection
# from google.colab import drive
# drive.mount('/content/drive')

from scipy.stats import zscore

import statsmodels.api as sm

# !pip install scikit-bio

In [17]:
# mixed_batch_data = pd.read_csv('/content/drive/MyDrive/curvefit_traits_merged_linearpf_onlyneccols.csv', index_col='subID')
mixed_batch_data = pd.read_csv('../../../data/subtlety_playfight_data/curvefit_traits_merged_linearpf_onlyneccols_fight.csv', index_col='subID')
mixed_batch_data.drop('Unnamed: 0', axis=1, inplace=True)
mixed_batch_data

,PSE_subt,range_subt,bias_subt,sigma_subt,PSE_pf,slope_pf,range_pf,bias_pf,social_skill,attn_switch,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,0.552951,0.900821,0.315504,0.103360,0.513054,0.784286,0.784286,0.452539,21.0,23.0,...,16.000000,20.0,0.0,38.0,28.000000,31.000000,34.0,39.0,56.0,3.0
30004.0,0.276896,0.805834,0.999458,0.076866,0.872907,0.469286,0.469286,0.170256,21.0,20.0,...,15.000000,25.0,11.0,38.0,26.181818,50.000000,50.0,46.0,56.0,3.0
30005.0,0.320583,0.710131,0.861730,0.115353,0.501696,0.842143,0.842143,0.490950,17.0,29.0,...,16.000000,20.0,21.0,51.0,39.000000,40.000000,43.0,19.0,41.0,5.0
30006.0,0.464823,0.989396,0.889572,0.079221,0.741046,0.674587,0.674587,0.000307,8.0,10.0,...,3.000000,25.0,0.0,18.0,41.000000,31.000000,44.0,57.0,30.0,4.0
30008.0,0.325118,0.582252,0.692710,0.172585,0.677591,0.511071,0.511071,0.314366,5.0,15.0,...,12.222222,28.0,4.0,27.0,46.000000,42.545455,46.0,50.0,45.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30344.0,0.361233,0.655715,0.794480,0.135840,0.492859,0.566786,0.566786,0.509343,27.0,18.0,...,16.000000,14.0,0.0,25.0,29.000000,49.000000,35.0,56.0,41.0,6.0
30345.0,0.475067,0.833333,1.000000,0.013915,0.639965,0.781136,0.781136,0.000457,15.0,14.0,...,5.000000,15.0,15.0,36.0,23.000000,37.000000,45.0,54.0,72.0,1.0
30346.0,0.426850,0.999914,0.961644,0.045409,0.412504,0.786429,0.786429,0.822185,16.0,25.0,...,8.000000,27.0,6.0,49.0,36.000000,36.000000,43.0,44.0,56.0,3.0
30348.0,0.729328,0.200238,0.444049,0.392303,0.468301,0.480714,0.480714,0.529344,8.0,7.0,...,2.000000,27.0,0.0,18.0,42.000000,41.000000,48.0,53.0,24.0,4.0
30352.0,0.392464,0.470243,0.528520,0.153343,0.353951,0.516786,0.516786,0.656196,8.0,6.0,...,4.000000,22.0,0.0,17.0,46.000000,47.000000,48.0,56.0,20.0,4.0

In [18]:
mixed_batch_data.isna().sum()

PSE_subt             0
range_subt           0
bias_subt            0
sigma_subt           0
PSE_pf               0
slope_pf             0
range_pf             0
bias_pf              0
social_skill         0
attn_switch          0
img                  0
attn_to_det          0
comm                 0
posAffect            0
negAffect            0
neuroticism          0
extraversion         0
openness             0
agreeableness        0
conscientiousness    0
loneliness           0
nfriends             1
dtype: int64

Looks like one subject is missing a value for `nfriends`. Let's just drop them as this will cause headaches later

In [19]:
mixed_batch_data = mixed_batch_data.dropna()
mixed_batch_data.shape

(274, 22)

In [20]:
mixed_batch_data.columns

Index(['PSE_subt', 'range_subt', 'bias_subt', 'sigma_subt', 'PSE_pf',
       'slope_pf', 'range_pf', 'bias_pf', 'social_skill', 'attn_switch', 'img',
       'attn_to_det', 'comm', 'posAffect', 'negAffect', 'neuroticism',
       'extraversion', 'openness', 'agreeableness', 'conscientiousness',
       'loneliness', 'nfriends'],
      dtype='object')

In [21]:
curve_param_cols = [
                  'PSE_subt',
                  'range_subt',
                  'bias_subt',
                  'range_pf',
                  'bias_pf'
                    ]
subt_param_cols = [
                  'PSE_subt',
                  'range_subt',
                  'bias_subt',
                   ]
pf_param_cols = [
                 'range_pf',
                 'bias_pf'
                 ]
trait_cols = [
              'social_skill', 'attn_switch', 'img', 'attn_to_det', 'comm',
              'posAffect',
              'negAffect',
              'neuroticism', 'extraversion', 'openness', 'agreeableness', 'conscientiousness',
              'loneliness',
              'nfriends'
       ]

social_cols = [
              'social_skill', 'attn_switch', 'img', 'attn_to_det', 'comm',
              'loneliness',
              'nfriends'
              ]

In [22]:
results_loc= '../../../results/subtlety_playfight_mixed/trait-beh/extra_analyses/'

In [23]:
# first, super important to z-score all the features in order to minimize the impact of different features being measured on different scales (just like PCA)
mixed_batch_data_zscored = mixed_batch_data.apply(zscore)
mixed_batch_data_zscored

,PSE_subt,range_subt,bias_subt,sigma_subt,PSE_pf,slope_pf,range_pf,bias_pf,social_skill,attn_switch,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,1.587100,1.139946,-2.182466,0.144545,-0.206179,0.740744,0.802900,0.052813,1.249255,1.403779,...,1.044306,-0.214096,-1.031925,0.328778,-1.032702,-1.533105,-1.890716,-0.771265,0.884033,-0.304004
30004.0,-0.836964,0.619923,1.390323,-0.452518,2.089832,-0.732085,-0.731401,-0.970100,1.249255,0.813345,...,0.862296,0.379919,0.470275,0.328778,-1.249254,1.402822,1.569992,0.078101,0.884033,-0.304004
30005.0,-0.453342,0.095984,0.670868,0.414827,-0.278646,1.011263,1.084710,0.192006,0.604630,2.584649,...,1.044306,-0.214096,1.835912,1.543459,0.277433,-0.142403,0.055932,-3.198024,-0.300924,0.449816
30006.0,0.813243,1.624863,0.816307,-0.399448,1.248505,0.227830,0.268579,-1.585944,-0.845776,-1.154772,...,-1.321823,0.379919,-1.031925,-1.539962,0.515640,-1.533105,0.272226,1.412818,-1.169892,0.072906
30008.0,-0.413524,-0.604109,-0.212045,1.704615,0.843637,-0.536710,-0.527871,-0.447886,-1.329245,-0.170714,...,0.356713,0.736328,-0.485670,-0.699029,1.111156,0.250927,0.704815,0.563453,0.015065,0.449816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30344.0,-0.096389,-0.201924,0.319575,0.876526,-0.335034,-0.276210,-0.256498,0.258657,2.216193,0.419721,...,1.044306,-0.926914,-1.031925,-0.885903,-0.913599,1.248300,-1.674422,1.291480,-0.300924,0.826726
30345.0,0.903194,0.770473,1.393153,-1.871185,0.603566,0.726018,0.787560,-1.585402,0.282318,-0.367525,...,-0.957803,-0.808111,1.016530,0.141904,-1.628218,-0.605970,0.488521,1.048804,2.147987,-1.057824
30346.0,0.479799,1.682444,1.192794,-1.161440,-0.847731,0.750763,0.813338,1.392306,0.443474,1.797403,...,-0.411773,0.617525,-0.212543,1.356585,-0.079876,-0.760493,0.055932,-0.164575,0.884033,-0.304004
30348.0,3.135886,-2.695502,-1.510981,6.656212,-0.491721,-0.678649,-0.675735,0.331135,-0.845776,-1.745207,...,-1.503832,0.617525,-1.031925,-1.539962,0.634743,0.012120,1.137403,0.927466,-1.643875,0.072906
30352.0,0.177852,-1.217317,-1.069726,1.270978,-1.221324,-0.509992,-0.500038,0.790810,-0.845776,-1.942019,...,-1.139813,0.023510,-1.031925,-1.633399,1.111156,0.939255,1.137403,1.291480,-1.959863,0.072906

# Linear regression

In [24]:
len(trait_cols)

14

In [1]:
from pymer4.models import Lmer, Lm

ModuleNotFoundError: No module named 'pymer4'

In [26]:
mixed_batch_data_zscored.head()

,PSE_subt,range_subt,bias_subt,sigma_subt,PSE_pf,slope_pf,range_pf,bias_pf,social_skill,attn_switch,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,1.587100,1.139946,-2.182466,0.144545,-0.206179,0.740744,0.802900,0.052813,1.249255,1.403779,...,1.044306,-0.214096,-1.031925,0.328778,-1.032702,-1.533105,-1.890716,-0.771265,0.884033,-0.304004
30004.0,-0.836964,0.619923,1.390323,-0.452518,2.089832,-0.732085,-0.731401,-0.970100,1.249255,0.813345,...,0.862296,0.379919,0.470275,0.328778,-1.249254,1.402822,1.569992,0.078101,0.884033,-0.304004
30005.0,-0.453342,0.095984,0.670868,0.414827,-0.278646,1.011263,1.084710,0.192006,0.604630,2.584649,...,1.044306,-0.214096,1.835912,1.543459,0.277433,-0.142403,0.055932,-3.198024,-0.300924,0.449816
30006.0,0.813243,1.624863,0.816307,-0.399448,1.248505,0.227830,0.268579,-1.585944,-0.845776,-1.154772,...,-1.321823,0.379919,-1.031925,-1.539962,0.515640,-1.533105,0.272226,1.412818,-1.169892,0.072906
30008.0,-0.413524,-0.604109,-0.212045,1.704615,0.843637,-0.536710,-0.527871,-0.447886,-1.329245,-0.170714,...,0.356713,0.736328,-0.485670,-0.699029,1.111156,0.250927,0.704815,0.563453,0.015065,0.449816

In [27]:
from scipy import stats

In [28]:
x = mixed_batch_data_zscored['openness']
y = mixed_batch_data_zscored['range_pf']
stats.pearsonr(x,y)

PearsonRResult(statistic=np.float64(-0.14517099076336462), pvalue=np.float64(0.01618245383746685))

In [30]:
x = mixed_batch_data_zscored['comm']
y = mixed_batch_data_zscored['bias_subt']
stats.pearsonr(x,y)

PearsonRResult(statistic=np.float64(-0.12728067802299373), pvalue=np.float64(0.03522083935901831))

# subtlety + playfight terms

In [14]:
param_list = ['PSE_subt','range_subt','bias_subt','range_pf','bias_pf']

all_ps = np.full((14,len(param_list)),np.nan) # for MCC
for t,trait in enumerate(trait_cols):
    print(f'\nTRAIT {trait}')
    model = Lm(f"{trait} ~ PSE_subt + range_subt + bias_subt + range_pf + bias_pf", data=mixed_batch_data_zscored)
    print(model.fit())

    for p,param in enumerate(param_list): # for MCC
        all_ps[t,p] = model.coefs['P-val'][param]

TRAIT social_skill
Formula: social_skill~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.020	 R^2_adj: 0.002

Log-likelihood: -385.953 	 AIC: 783.906	 BIC: 805.585

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.060  268  -0.000  1.000
PSE_subt      -0.044  -0.211    0.123  0.085  268  -0.521  0.603
range_subt     0.139  -0.023    0.300  0.082  268   1.692  0.092   .
bias_subt     -0.137  -0.298    0.024  0.082  268  -1.677  0.095   .
range_pf      -0.005  -0.144    0.135  0.071  268  -0.066  0.947
bias_pf        0.014  -0.106    0.134  0.061  268   0.226  0.822

TRAIT attn_switch
Formula: attn_switch~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.008	 R^2_adj: -0.010

Log-likelihood: -387.672 	 AIC: 787.344	 BIC: 809.023

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  268   0.000  1.000
PSE_subt      -0.006  -0.174    0.162  0.085  268  -0.069  0.945
range_subt     0.015  -0.147    0.177  0.082  268   0.180  0.857
bias_subt     -0.002  -0.164    0.160  0.082  268  -0.021  0.983
range_pf       0.076  -0.064    0.217  0.071  268   1.066  0.287
bias_pf        0.033  -0.087    0.154  0.061  268   0.544  0.587

TRAIT img
Formula: img~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.005	 R^2_adj: -0.013

Log-likelihood: -388.045 	 AIC: 788.089	 BIC: 809.768

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  268   0.000  1.000
PSE_subt      -0.030  -0.198    0.138  0.085  268  -0.353  0.724
range_subt    -0.007  -0.169    0.156  0.083  268  -0.082  0.935
bias_subt     -0.010  -0.172    0.152  0.082  268  -0.125  0.900
range_pf       0.019  -0.122    0.160  0.071  268   0.264  0.792
bias_pf        0.063  -0.058    0.184  0.061  268   1.032  0.303

TRAIT attn_to_det
Formula: attn_to_det~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.008	 R^2_adj: -0.010

Log-likelihood: -387.647 	 AIC: 787.293	 BIC: 808.972

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  268   0.000  1.000
PSE_subt      -0.032  -0.200    0.136  0.085  268  -0.378  0.706
range_subt    -0.030  -0.192    0.132  0.082  268  -0.363  0.717
bias_subt      0.046  -0.116    0.208  0.082  268   0.556  0.579
range_pf      -0.032  -0.172    0.109  0.071  268  -0.444  0.657
bias_pf        0.038  -0.083    0.158  0.061  268   0.613  0.541

TRAIT comm
Formula: comm~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.019	 R^2_adj: 0.001

Log-likelihood: -386.175 	 AIC: 784.349	 BIC: 806.028

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.061  268  -0.000  1.000
PSE_subt      -0.013  -0.180    0.154  0.085  268  -0.154  0.878
range_subt     0.037  -0.125    0.198  0.082  268   0.447  0.655
bias_subt     -0.147  -0.308    0.014  0.082  268  -1.796  0.074   .
range_pf       0.004  -0.135    0.144  0.071  268   0.060  0.952
bias_pf        0.043  -0.077    0.163  0.061  268   0.701  0.484

TRAIT posAffect
Formula: posAffect~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.041	 R^2_adj: 0.023

Log-likelihood: -383.095 	 AIC: 778.190	 BIC: 799.869

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.118    0.118  0.060  268   0.000  1.000
PSE_subt      -0.030  -0.195    0.135  0.084  268  -0.360  0.719
range_subt    -0.168  -0.328   -0.008  0.081  268  -2.073  0.039   *
bias_subt      0.021  -0.138    0.181  0.081  268   0.266  0.791
range_pf       0.173   0.035    0.312  0.070  268   2.470  0.014   *
bias_pf       -0.055  -0.174    0.063  0.060  268  -0.920  0.358

TRAIT negAffect
Formula: negAffect~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.022	 R^2_adj: 0.004

Log-likelihood: -385.724 	 AIC: 783.448	 BIC: 805.127

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.060  268  -0.000  1.000
PSE_subt       0.012  -0.155    0.178  0.085  268   0.138  0.890
range_subt     0.074  -0.087    0.235  0.082  268   0.902  0.368
bias_subt     -0.035  -0.196    0.126  0.082  268  -0.430  0.667
range_pf       0.097  -0.042    0.237  0.071  268   1.370  0.172
bias_pf        0.049  -0.071    0.169  0.061  268   0.801  0.424

TRAIT neuroticism
Formula: neuroticism~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.004	 R^2_adj: -0.014

Log-likelihood: -388.207 	 AIC: 788.414	 BIC: 810.093

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  268   0.000  1.000
PSE_subt      -0.013  -0.181    0.156  0.085  268  -0.149  0.881
range_subt     0.047  -0.115    0.210  0.083  268   0.574  0.566
bias_subt     -0.014  -0.176    0.148  0.082  268  -0.167  0.868
range_pf       0.037  -0.104    0.178  0.072  268   0.514  0.608
bias_pf        0.013  -0.108    0.134  0.061  268   0.210  0.834

TRAIT extraversion
Formula: extraversion~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.028	 R^2_adj: 0.010

Log-likelihood: -384.897 	 AIC: 781.793	 BIC: 803.472

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.060  268   0.000  1.000
PSE_subt      -0.081  -0.248    0.085  0.084  268  -0.964  0.336
range_subt    -0.100  -0.261    0.060  0.082  268  -1.231  0.219
bias_subt      0.037  -0.124    0.197  0.081  268   0.450  0.653
range_pf       0.084  -0.055    0.223  0.071  268   1.188  0.236
bias_pf       -0.051  -0.171    0.068  0.061  268  -0.843  0.400

TRAIT openness
Formula: openness~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.038	 R^2_adj: 0.020

Log-likelihood: -383.501 	 AIC: 779.003	 BIC: 800.681

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.118    0.118  0.060  268  -0.000  1.000
PSE_subt       0.049  -0.116    0.214  0.084  268   0.583  0.560
range_subt     0.043  -0.117    0.203  0.081  268   0.529  0.598
bias_subt      0.131  -0.028    0.291  0.081  268   1.621  0.106
range_pf      -0.214  -0.352   -0.076  0.070  268  -3.043  0.003  **
bias_pf       -0.043  -0.161    0.076  0.060  268  -0.706  0.481

TRAIT agreeableness
Formula: agreeableness~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.021	 R^2_adj: 0.003

Log-likelihood: -385.880 	 AIC: 783.760	 BIC: 805.439

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.060  268   0.000  1.000
PSE_subt       0.135  -0.032    0.302  0.085  268   1.593  0.112
range_subt    -0.028  -0.189    0.133  0.082  268  -0.344  0.731
bias_subt      0.077  -0.084    0.238  0.082  268   0.943  0.347
range_pf      -0.078  -0.217    0.062  0.071  268  -1.093  0.275
bias_pf       -0.077  -0.197    0.043  0.061  268  -1.260  0.209

TRAIT conscientiousness
Formula: conscientiousness~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.019	 R^2_adj: 0.001

Log-likelihood: -386.187 	 AIC: 784.373	 BIC: 806.052

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.061  268  -0.000  1.000
PSE_subt       0.049  -0.118    0.216  0.085  268   0.573  0.567
range_subt    -0.077  -0.239    0.084  0.082  268  -0.943  0.347
bias_subt      0.108  -0.053    0.269  0.082  268   1.321  0.188
range_pf       0.092  -0.048    0.231  0.071  268   1.291  0.198
bias_pf       -0.035  -0.155    0.085  0.061  268  -0.572  0.568

TRAIT loneliness
Formula: loneliness~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.017	 R^2_adj: -0.001

Log-likelihood: -386.388 	 AIC: 784.777	 BIC: 806.455

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.061  268  -0.000  1.000
PSE_subt      -0.077  -0.244    0.090  0.085  268  -0.910  0.364
range_subt     0.132  -0.029    0.294  0.082  268   1.612  0.108
bias_subt     -0.090  -0.251    0.071  0.082  268  -1.104  0.271
range_pf      -0.030  -0.170    0.110  0.071  268  -0.420  0.675
bias_pf       -0.073  -0.193    0.047  0.061  268  -1.202  0.230

TRAIT nfriends
Formula: nfriends~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.013	 R^2_adj: -0.005

Log-likelihood: -386.986 	 AIC: 785.971	 BIC: 807.650

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.061  268   0.000  1.000
PSE_subt       0.003  -0.165    0.170  0.085  268   0.032  0.975
range_subt    -0.040  -0.202    0.122  0.082  268  -0.484  0.629
bias_subt      0.059  -0.103    0.220  0.082  268   0.719  0.473
range_pf      -0.007  -0.147    0.133  0.071  268  -0.101  0.919
bias_pf        0.091  -0.030    0.211  0.061  268   1.482  0.140

In [15]:
## MCC
result_bool = np.full_like(all_ps,np.nan)
corrected_p = np.full_like(all_ps,np.nan)
for p, param in enumerate(param_list):
    result_bool[:,p], corrected_p[:,p] = fdrcorrection(all_ps[:,p])
    print(param, np.where(result_bool[:,p])[0], np.array(trait_cols)[np.where(result_bool[:,p])[0]])
# i.e., openness-range_pf is the only relationship that survives MCC

PSE_subt [] []
range_subt [] []
bias_subt [] []
range_pf [9] ['openness']
bias_pf [] []

# only subtlety terms

In [70]:
param_list = ['PSE_subt','range_subt','bias_subt']

all_ps_subt = np.full((14,len(param_list)),np.nan) # for MCC
for t,trait in enumerate(trait_cols):
    print(f'\nTRAIT {trait}')
    model = Lm(f"{trait} ~ PSE_subt + range_subt + bias_subt", data=mixed_batch_data_zscored)
    print(model.fit())

    for p,param in enumerate(param_list): # for MCC
        all_ps_subt[t,p] = model.coefs['P-val'][param]

TRAIT social_skill
Formula: social_skill~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.020	 R^2_adj: 0.009

Log-likelihood: -385.981 	 AIC: 779.962	 BIC: 794.414

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.060  270  -0.000  1.000
PSE_subt      -0.045  -0.211    0.121  0.084  270  -0.533  0.595
range_subt     0.137  -0.017    0.290  0.078  270   1.755  0.080   .
bias_subt     -0.137  -0.291    0.017  0.078  270  -1.757  0.080   .

TRAIT attn_switch
Formula: attn_switch~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.003	 R^2_adj: -0.008

Log-likelihood: -388.426 	 AIC: 784.853	 BIC: 799.305

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  270   0.000  1.000
PSE_subt      -0.004  -0.172    0.163  0.085  270  -0.049  0.961
range_subt     0.040  -0.114    0.195  0.078  270   0.512  0.609
bias_subt      0.025  -0.131    0.180  0.079  270   0.314  0.753

TRAIT img
Formula: img~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.001	 R^2_adj: -0.010

Log-likelihood: -388.634 	 AIC: 785.269	 BIC: 799.721

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  270   0.000  1.000
PSE_subt      -0.032  -0.200    0.136  0.085  270  -0.378  0.706
range_subt    -0.002  -0.157    0.152  0.079  270  -0.031  0.975
bias_subt      0.001  -0.155    0.156  0.079  270   0.008  0.993

TRAIT attn_to_det
Formula: attn_to_det~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.006	 R^2_adj: -0.005

Log-likelihood: -387.929 	 AIC: 783.857	 BIC: 798.310

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.061  270   0.000  1.000
PSE_subt      -0.035  -0.202    0.132  0.085  270  -0.414  0.679
range_subt    -0.042  -0.196    0.112  0.078  270  -0.540  0.590
bias_subt      0.039  -0.116    0.194  0.079  270   0.492  0.623

TRAIT comm
Formula: comm~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.017	 R^2_adj: 0.006

Log-likelihood: -386.430 	 AIC: 780.859	 BIC: 795.312

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.060  270  -0.000  1.000
PSE_subt      -0.015  -0.181    0.152  0.085  270  -0.175  0.861
range_subt     0.037  -0.117    0.190  0.078  270   0.470  0.639
bias_subt     -0.142  -0.296    0.012  0.078  270  -1.814  0.071   .

TRAIT posAffect
Formula: posAffect~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.016	 R^2_adj: 0.006

Log-likelihood: -386.520 	 AIC: 781.039	 BIC: 795.492

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.060  270   0.000  1.000
PSE_subt      -0.021  -0.187    0.146  0.085  270  -0.243  0.808
range_subt    -0.106  -0.259    0.048  0.078  270  -1.356  0.176
bias_subt      0.072  -0.083    0.226  0.078  270   0.912  0.362

TRAIT negAffect
Formula: negAffect~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.013	 R^2_adj: 0.002

Log-likelihood: -387.050 	 AIC: 782.100	 BIC: 796.552

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.060  270  -0.000  1.000
PSE_subt       0.014  -0.153    0.180  0.085  270   0.160  0.873
range_subt     0.106  -0.048    0.260  0.078  270   1.357  0.176
bias_subt     -0.001  -0.155    0.154  0.079  270  -0.010  0.992

TRAIT neuroticism
Formula: neuroticism~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.003	 R^2_adj: -0.008

Log-likelihood: -388.369 	 AIC: 784.738	 BIC: 799.190

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  270   0.000  1.000
PSE_subt      -0.012  -0.179    0.156  0.085  270  -0.139  0.890
range_subt     0.060  -0.095    0.214  0.078  270   0.762  0.447
bias_subt     -0.001  -0.157    0.154  0.079  270  -0.015  0.988

TRAIT extraversion
Formula: extraversion~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.021	 R^2_adj: 0.010

Log-likelihood: -385.940 	 AIC: 779.879	 BIC: 794.332

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.060  270   0.000  1.000
PSE_subt      -0.076  -0.242    0.090  0.084  270  -0.897  0.371
range_subt    -0.069  -0.223    0.084  0.078  270  -0.893  0.373
bias_subt      0.059  -0.095    0.213  0.078  270   0.753  0.452

TRAIT openness
Formula: openness~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.002	 R^2_adj: -0.009

Log-likelihood: -388.489 	 AIC: 784.977	 BIC: 799.430

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.120    0.120  0.061  270  -0.000  1.000
PSE_subt       0.042  -0.126    0.210  0.085  270   0.493  0.622
range_subt    -0.030  -0.185    0.125  0.078  270  -0.383  0.702
bias_subt      0.061  -0.095    0.216  0.079  270   0.769  0.443

TRAIT agreeableness
Formula: agreeableness~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.010	 R^2_adj: -0.001

Log-likelihood: -387.351 	 AIC: 782.701	 BIC: 797.154

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.119    0.119  0.061  270   0.000  1.000
PSE_subt       0.135  -0.032    0.302  0.085  270   1.594  0.112
range_subt    -0.052  -0.206    0.101  0.078  270  -0.670  0.503
bias_subt      0.047  -0.108    0.201  0.079  270   0.592  0.554

TRAIT conscientiousness
Formula: conscientiousness~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.012	 R^2_adj: 0.001

Log-likelihood: -387.175 	 AIC: 782.351	 BIC: 796.803

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.061  270  -0.000  1.000
PSE_subt       0.054  -0.113    0.221  0.085  270   0.637  0.524
range_subt    -0.044  -0.198    0.110  0.078  270  -0.565  0.573
bias_subt      0.134  -0.021    0.289  0.079  270   1.706  0.089   .

TRAIT loneliness
Formula: loneliness~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.011	 R^2_adj: 0.000

Log-likelihood: -387.236 	 AIC: 782.471	 BIC: 796.924

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.119    0.119  0.061  270  -0.000  1.000
PSE_subt      -0.075  -0.242    0.092  0.085  270  -0.888  0.375
range_subt     0.124  -0.029    0.278  0.078  270   1.593  0.112
bias_subt     -0.106  -0.260    0.049  0.079  270  -1.343  0.180

TRAIT nfriends
Formula: nfriends~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.005	 R^2_adj: -0.006

Log-likelihood: -388.104 	 AIC: 784.208	 BIC: 798.661

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept      0.000  -0.120    0.120  0.061  270   0.000  1.000
PSE_subt      -0.002  -0.169    0.166  0.085  270  -0.019  0.985
range_subt    -0.046  -0.200    0.109  0.078  270  -0.581  0.562
bias_subt      0.064  -0.091    0.219  0.079  270   0.810  0.418

In [71]:
## MCC
result_bool = np.full_like(all_ps,np.nan)
corrected_p = np.full_like(all_ps,np.nan)
for p, param in enumerate(param_list):
    result_bool[:,p], corrected_p[:,p] = fdrcorrection(all_ps[:,p])
    print(param, np.where(result_bool[:,p])[0], np.array(trait_cols)[np.where(result_bool[:,p])[0]])
# i.e., openness-range_pf is the only relationship that survives MCC

PSE_subt [] []
range_subt [] []
bias_subt [] []

# only playfight terms

In [72]:
param_list = ['range_pf','bias_pf']

all_ps = np.full((14,len(param_list)),np.nan) # for MCC
for t,trait in enumerate(trait_cols):
    print(f'\nTRAIT {trait}')
    model = Lm(f"{trait} ~ range_pf + bias_pf", data=mixed_batch_data_zscored)
    print(model.fit())

    for p,param in enumerate(param_list): # for MCC
        all_ps[t,p] = model.coefs['P-val'][param]

TRAIT social_skill
Formula: social_skill~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.000	 R^2_adj: -0.007

Log-likelihood: -388.788 	 AIC: 783.576	 BIC: 794.415

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.120    0.120  0.061  271  -0.000  1.000
range_pf      0.003  -0.117    0.123  0.061  271   0.047  0.963
bias_pf       0.000  -0.120    0.120  0.061  271   0.001  0.999

TRAIT attn_switch
Formula: attn_switch~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.008	 R^2_adj: 0.001

Log-likelihood: -387.690 	 AIC: 781.381	 BIC: 792.220

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.061  271   0.000  1.000
range_pf      0.082  -0.038    0.201  0.061  271   1.348  0.179
bias_pf       0.033  -0.086    0.152  0.061  271   0.544  0.587

TRAIT img
Formula: img~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.005	 R^2_adj: -0.003

Log-likelihood: -388.171 	 AIC: 782.342	 BIC: 793.182

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.061  271   0.000  1.000
range_pf      0.010  -0.109    0.130  0.061  271   0.171  0.865
bias_pf       0.066  -0.054    0.185  0.061  271   1.085  0.279

TRAIT attn_to_det
Formula: attn_to_det~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.003	 R^2_adj: -0.005

Log-likelihood: -388.398 	 AIC: 782.795	 BIC: 793.634

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.061  271   0.000  1.000
range_pf     -0.030  -0.149    0.090  0.061  271  -0.489  0.625
bias_pf       0.046  -0.074    0.165  0.061  271   0.753  0.452

TRAIT comm
Formula: comm~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.002	 R^2_adj: -0.005

Log-likelihood: -388.503 	 AIC: 783.006	 BIC: 793.845

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.119    0.119  0.061  271  -0.000  1.000
range_pf     -0.035  -0.155    0.085  0.061  271  -0.575  0.566
bias_pf       0.031  -0.089    0.151  0.061  271   0.510  0.610

TRAIT posAffect
Formula: posAffect~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.013	 R^2_adj: 0.005

Log-likelihood: -387.066 	 AIC: 780.131	 BIC: 790.971

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.06  271   0.000  1.000
range_pf      0.106  -0.013    0.225  0.06  271   1.749  0.081   .
bias_pf      -0.042  -0.160    0.077  0.06  271  -0.687  0.493

TRAIT negAffect
Formula: negAffect~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.016	 R^2_adj: 0.009

Log-likelihood: -386.604 	 AIC: 779.208	 BIC: 790.047

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.119    0.119  0.06  271  -0.000  1.000
range_pf      0.117  -0.002    0.236  0.06  271   1.943  0.053   .
bias_pf       0.041  -0.078    0.160  0.06  271   0.677  0.499

TRAIT neuroticism
Formula: neuroticism~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.003	 R^2_adj: -0.005

Log-likelihood: -388.400 	 AIC: 782.799	 BIC: 793.639

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.061  271   0.000  1.000
range_pf      0.052  -0.068    0.171  0.061  271   0.853  0.394
bias_pf       0.010  -0.109    0.130  0.061  271   0.172  0.864

TRAIT extraversion
Formula: extraversion~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.003	 R^2_adj: -0.004

Log-likelihood: -388.318 	 AIC: 782.636	 BIC: 793.475

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.061  271   0.000  1.000
range_pf      0.049  -0.071    0.168  0.061  271   0.802  0.423
bias_pf      -0.035  -0.154    0.085  0.061  271  -0.574  0.566

TRAIT openness
Formula: openness~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.023	 R^2_adj: 0.015

Log-likelihood: -385.648 	 AIC: 777.295	 BIC: 788.135

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.118    0.118  0.06  271  -0.000  1.000
range_pf     -0.143  -0.262   -0.025  0.06  271  -2.386  0.018   *
bias_pf      -0.040  -0.158    0.078  0.06  271  -0.665  0.507

TRAIT agreeableness
Formula: agreeableness~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.010	 R^2_adj: 0.003

Log-likelihood: -387.403 	 AIC: 780.806	 BIC: 791.645

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.06  271   0.000  1.000
range_pf     -0.054  -0.173    0.066  0.06  271  -0.886  0.377
bias_pf      -0.083  -0.202    0.037  0.06  271  -1.364  0.174

TRAIT conscientiousness
Formula: conscientiousness~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.011	 R^2_adj: 0.003

Log-likelihood: -387.327 	 AIC: 780.654	 BIC: 791.494

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.119    0.119  0.06  271  -0.000  1.000
range_pf      0.101  -0.019    0.220  0.06  271   1.663  0.098   .
bias_pf      -0.027  -0.146    0.092  0.06  271  -0.450  0.653

TRAIT loneliness
Formula: loneliness~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.007	 R^2_adj: -0.001

Log-likelihood: -387.888 	 AIC: 781.776	 BIC: 792.616

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.00  -0.119    0.119  0.061  271  -0.000  1.000
range_pf      -0.01  -0.129    0.110  0.061  271  -0.159  0.873
bias_pf       -0.08  -0.199    0.039  0.061  271  -1.319  0.188

TRAIT nfriends
Formula: nfriends~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.009	 R^2_adj: 0.002

Log-likelihood: -387.498 	 AIC: 780.997	 BIC: 791.836

Fixed effects:

           Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     0.000  -0.119    0.119  0.060  271   0.000  1.000
range_pf     -0.003  -0.122    0.117  0.061  271  -0.044  0.965
bias_pf       0.097  -0.022    0.216  0.061  271   1.601  0.110

In [76]:
all_ps.shape

(14, 2)

In [73]:
## MCC
result_bool = np.full_like(all_ps,np.nan)
corrected_p = np.full_like(all_ps,np.nan)
for p, param in enumerate(param_list):
    result_bool[:,p], corrected_p[:,p] = fdrcorrection(all_ps[:,p])
    print(param, np.where(result_bool[:,p])[0], np.array(trait_cols)[np.where(result_bool[:,p])[0]])
# i.e., openness-range_pf is the only relationship that survives MCC

range_pf [] []
bias_pf [] []

 # openness vs. params
 - does combining both expts improve the model?

In [62]:
trait = 'openness'

In [63]:
model = Lm(f"{trait} ~ PSE_subt + range_subt + bias_subt", data=mixed_batch_data_zscored)
print(model.fit())

Formula: openness~PSE_subt+range_subt+bias_subt

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.002	 R^2_adj: -0.009

Log-likelihood: -388.489 	 AIC: 784.977	 BIC: 799.430

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.120    0.120  0.061  270  -0.000  1.000
PSE_subt       0.042  -0.126    0.210  0.085  270   0.493  0.622
range_subt    -0.030  -0.185    0.125  0.078  270  -0.383  0.702
bias_subt      0.061  -0.095    0.216  0.079  270   0.769  0.443

In [64]:
model = Lm(f"{trait} ~  range_pf + bias_pf", data=mixed_batch_data_zscored)
print(model.fit())

Formula: openness~range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.023	 R^2_adj: 0.015

Log-likelihood: -385.648 	 AIC: 777.295	 BIC: 788.135

Fixed effects:

           Estimate  2.5_ci  97.5_ci    SE   DF  T-stat  P-val Sig
Intercept    -0.000  -0.118    0.118  0.06  271  -0.000  1.000
range_pf     -0.143  -0.262   -0.025  0.06  271  -2.386  0.018   *
bias_pf      -0.040  -0.158    0.078  0.06  271  -0.665  0.507

In [65]:
model = Lm(f"{trait} ~ PSE_subt + range_subt + bias_subt + range_pf + bias_pf", data=mixed_batch_data_zscored)
print(model.fit())

Formula: openness~PSE_subt+range_subt+bias_subt+range_pf+bias_pf

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.038	 R^2_adj: 0.020

Log-likelihood: -383.501 	 AIC: 779.003	 BIC: 800.681

Fixed effects:

            Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept     -0.000  -0.118    0.118  0.060  268  -0.000  1.000
PSE_subt       0.049  -0.116    0.214  0.084  268   0.583  0.560
range_subt     0.043  -0.117    0.203  0.081  268   0.529  0.598
bias_subt      0.131  -0.028    0.291  0.081  268   1.621  0.106
range_pf      -0.214  -0.352   -0.076  0.070  268  -3.043  0.003  **
bias_pf       -0.043  -0.161    0.076  0.060  268  -0.706  0.481